pipeline {

    agent any
    environment {
        projectProva = "$WORKSPACE/ProvaN3_app_fast"
    }

    stages {
        stage ('Preparando Ambiente') {
            steps {
                echo 'Construindo ambiente wrapper'
                dir ("$projectProva") {
                    sh 'gradle wrapper'
                }
            }
        }
        stage ('Test Unit') {
            steps {
                echo 'Testando Unidade'
                dir ("$projectProva") {
                    sh './gradlew test'
                }
            }
        }
    }
}